config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :welcome, only: :show

  resources :news
  resources :cities
  resources :android_packages do
    member do
      get :qrcode
    end
  end
  resource :audit, only: [] do
    get :identify
    get :people

    get :show, to: redirect('/audit/identify')
  end

  namespace :editormd do
    resources :images, only: :create
  end

  namespace :api, defaults: { format: 'json' } do
    resources :news, only: :index
    resources :cities, only: :index
    resource :identity, only: [] do
      post :identify
      get :abilities
      post :use_count
    end
    resource :update, only: :show
  end

  root to: 'welcomes#show'
end

app/models/news.rb
class News < ApplicationRecord
  CATEGORIES = {
    '社保政策' => 'policies',
    '社保通知' => 'notifications',
    '社保服务' => 'services'
  }

  has_attached_file :thumbnail_image, styles: { thumb: "100x80>" }
  validates_attachment_content_type :thumbnail_image, content_type: /\Aimage\/.*\Z/

  def thumbnail(request)
    if thumbnail_url.present?
      thumbnail_url
    elsif thumbnail_image.present?
      "#{request.scheme}://#{request.host_with_port}#{thumbnail_image.url}"
    end
  end

  def source(request)
    if source_content.present?
      "#{request.scheme}://#{request.host_with_port}/news/#{id}"
    elsif source_url.present?
      source_url
    end
  end
end

app/controllers/api/news_controller.rb
class Api::NewsController < Api::ApplicationController
  def index
    @page = (params[:page] || 1).to_i
    @per = (params[:per] || 10).to_i

    news_klass =
      if params[:category]
        News.where(category: params[:category])
      else
        News
      end

    @finished = news_klass.count <= @page * 10
    @news = news_klass.order(created_at: :desc).page(@page).per(@per)
  end
end

app/controllers/news_controller.rb
class NewsController < ResourceController
  def show
    render :show, layout: false
  end

  private
    def resource_class
      News
    end

    def resource_path
      resources_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:news).permit(:title, :author, :raw_source_content, :source_content,
        :source_url, :thumbnail_url, :thumbnail_image, :category)
    end
end

app/views/news/_form.html.erb
<%= simple_form_for(resource, html: { class: 'form-horizontal' }) do |f| %>
  <div class="col-md-7">
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :author %>
      <%= f.input :category, collection: News::CATEGORIES %>
      <div class="form-group text optional news_source_content">
        <%= f.label :source_content, class: 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <div class="editormd" id="editormd">
            <%= f.input_field :raw_source_content, class: 'editormd-markdown-textarea hidden' %>
            <%= f.input_field :source_content, class: 'editormd-html-textarea hidden' %>
          </div>
        </div>
      </div>
      <%= f.input :source_url %>
      <%= f.input :thumbnail_image %>
      <%= f.input :thumbnail_url %>
    </div>

    <div class="form-actions pull-right">
      <%= f.button :submit %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  var $container = $("body > .container"),
      $editormd = $("#editormd");

  var width = $container.offset().left + $container.width() - $editormd.offset().left;

  var editor = editormd("editormd", {
    width: width,
    height: 480,
    path: "/editormd/lib/",
    htmlDecode: true,
    saveHTMLToTextarea: true,
    previewCodeHighlight: false,
    imageUpload: true,
    imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
    imageUploadURL: "/editormd/images",
    placeholder: "您可以使用Markdown编辑新闻内容...",
    toolbarIcons: [
        "undo", "redo", "|",
        "bold", "del", "italic", "quote", "|",
        "h1", "h2", "h3", "|",
        // "h4", "h5", "h6", "|",
        "list-ul", "list-ol", "|",
        "link", "reference-link", "image", "table", "hr", "datetime", "html-entities", "|",
        "watch", "preview", "fullscreen", "|",
        "help", "info"
    ],
    // toolbarIconsClass: {
    //   h4: "fa-align-left",
    //   h5: "fa-align-center",
    //   h6: "fa-align-right"
    // },
    // lang: {
    //   toolbar: {
    //     h4: "左对齐",
    //     h5: "居中",
    //     h6: "右对齐"
    //   }
    // },
  });

  $(window).resize(function() {
    var width = $container.offset().left + $container.width() - $editormd.offset().left;
    $editormd.width(width);
  });
</script>

<style type="text/css">
  .fa-align-left, .fa-align-center, .fa-align-right {
    font-size: 0;
  }

  .fa-align-left::before, .fa-align-center::before, .fa-align-right::before {
    font-size: 14px;
  }
</style>

app/views/news/index.html.erb
<% @category = params[:category] %>
<% @resources = @resources.where(category: @category) if @category %>
<% def nav_item title, key = nil
  content_tag :li, @category == key && { class: 'active' } do
    link_to(title,  news_index_path(key && { category: key}))
  end
end %>

<h2 class="page-header">
  新闻管理
</h2>

<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <%= nav_item "全部类别" %>
      <% News::CATEGORIES.each do |title, key| %>
        <%= nav_item title, key %>
      <% end %>
      <li class="divider"></li>
      <li><%= link_to("新建新闻", new_news_path) %></li>
    </ul>
  </div>

  <div class="col-md-9 data-table">
    <%= wice_index_for @resources, class: "table table-striped table-hover" do |i| %>
      <%= i.attribute :id %>
      <%= i.attribute :title, searchable: true %>
      <%= i.attribute :author, searchable: true %>
      <%= i.attribute :created_at, format: :short %>
      <%= i.attribute :updated_at, format: :short %>
      <%= i.actions do |a| %>
        <%= a.action_link :show do %>
          <%= link_to "预览", i.object.source(request), class: "action_show action", target: "_blank" %>
        <% end %>
        <%= a.action_link :edit %>
        <%= a.action_link :destroy %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/news/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @resource.title %></title>
    <%= stylesheet_link_tag "preview" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body class="markdown-body">
    <h1 class="title"><%= @resource.title %></h1>
    <div class="meta-data">
      <span><%= l @resource.created_at, format: :date %></span>
      <span><%= @resource.author %></span>
    </div>

    <div class="content">
      <%= raw @resource.source_content %>
    </div>
  </body>
</html>