config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :welcome, only: :show

  resources :news
  resources :cities
  resources :android_packages do
    member do
      get :qrcode
    end
  end
  resource :audit, only: [] do
    get :identify
    get :people

    get :show, to: redirect('/audit/identify')
  end

  namespace :editormd do
    resources :images, only: :create
  end

  namespace :api, defaults: { format: 'json' } do
    resources :news, only: :index
    resources :cities, only: :index
    resource :identity, only: [] do
      post :identify
      get :abilities
      post :use_count
    end
    resource :update, only: :show
  end

  root to: 'welcomes#show'
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  def show
    redirect_to action: :identify
  end

  def identify
    @callings = IdentifyCalling.all
  end

  def people
    @people = Person.all
  end
end

app/views/audits/identify.html.erb
<h2 class="page-header">
  审计记录
</h2>

<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><%= link_to("认证接口调用记录", identify_audit_path) %></li>
      <li><%= link_to("认证人员记录", people_audit_path) %></li>
    </ul>
  </div>

  <div class="col-md-9 data-table">
    <% blank = '<span class="blank">未知</span>'.html_safe %>
    <%= wice_index_for @callings, class: "table table-striped table-hover" do |i| %>
      <%= i.attribute :name, searchable: true %>
      <%= i.attribute :id_number, format: :watermark, searchable: true %>
      <%= i.attribute :remote_ip, searchable: true %>
      <%= i.attribute :created_at, format: :long %>
      <%= i.attribute :endpoint do |calling| %>
        <%= IdentifyCalling::ENDPOINTS.key(calling.endpoint) || blank %>
      <% end %>
      <%= i.attribute :validity do |calling| %>
        <%= IdentifyCalling::VALIDITIES.key(calling.validity) || blank %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/audits/people.html.erb
<h2 class="page-header">
  审计记录
</h2>

<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to("认证接口调用记录", identify_audit_path) %></li>
      <li class="active"><%= link_to("认证人员记录", people_audit_path) %></li>
    </ul>
  </div>

  <div class="col-md-9 data-table">
    <% blank = '<span class="blank">未知</span>'.html_safe %>
    <%= wice_index_for @people, class: "table table-striped table-hover" do |i| %>
      <%= i.attribute :name, searchable: true %>
      <%= i.attribute :id_number, format: :watermark, searchable: true %>
      <%= i.attribute :created_at, format: :short %>
      <%= i.attribute :updated_at, format: :short %>
      <%= i.attribute :identify_callings_count %>
      <%= i.attribute :accepted_identify_callings_count %>
    <% end %>
  </div>
</div>