web/router.ex
defmodule Scanner.Router do
  use Scanner.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Scanner do
    pipe_through :browser

    resources "/news", NewsController
  end

  scope "/api", Scanner.API do
    pipe_through :api

    get "/identity/abilities", IdentityController, :abilities
    post "/identity/identify", IdentityController, :identify

    get "/news", NewsController, :index
  end
end

web/models/news.ex
defmodule Scanner.News do
  use Scanner.Web, :model

  @derive {Poison.Encoder, only: [:content, :subtitle, :title, :author, :thumbnail_url, :source_url]}

  schema "news" do
    field :content, :string
    field :title, :string
    field :subtitle, :string
    field :author, :string
    field :thumbnail_url, :string
    field :source_url, :string

    field :type, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content, :title, :author, :thumbnail_url, :source_url])
    |> validate_required([:content, :title, :author, :thumbnail_url])
  end
end

web/controllers/api/news_controller.ex
defmodule Scanner.API.NewsController do
  use Scanner.Web, :controller
  use Scanner.JSONHelper

  alias Scanner.News

  defdelegate fetch_all_news(conn, _options), to: Scanner.NewsController
  plug :fetch_all_news when action == :index

  def index conn, params do
    %{news: news, page: page, finished: finished} = conn.assigns
    json_success conn, %{data: news, page: page, finished: finished}
  end
end

web/controllers/news_controller.ex
defmodule Scanner.NewsController do
  use Scanner.Web, :controller

  alias Scanner.News

  plug :fetch_all_news when action == :index
  plug :fetch_one_news when action in [:edit, :update]

  def index conn, params do
    conn
    |> render("index.html")
  end

  def edit conn, params do
    conn
    |> render("edit.html")
  end

  def fetch_all_news conn, _options do
    params = conn.params
    page = if params["page"], do: String.to_integer(params["page"]), else: 1
    offset = (page - 1) * 10
    query =
      if type = params["type"] do
        from n in News, where: n.type == ^type
      else
        News
      end

    query =
      if search = params["search"] do
        from n in query, where: like(n.title, ^("%#{search}%")) or like(n.subtitle, ^("%#{search}%")) or like(n.author, ^("%#{search}%"))
      else
        query
      end

    news = Repo.all(from n in query, limit: 10, offset: ^offset)
    count = Repo.one(from n in query, select: count("id"))
    finished = count <= offset + 10

    conn
    |> assign(:news, news)
    |> assign(:start, offset)
    |> assign(:stop, if(finished, do: count, else: offset + 10))
    |> assign(:total, count)
    |> assign(:page, page)
    |> assign(:finished, finished)
  end

  def fetch_one_news conn, _options do
    id = String.to_integer(conn.params["id"])
    news = Repo.get(News, id)

    conn
    |> assign(:id, id)
    |> assign(:news, news)
  end
end

web/views/news_view.ex
defmodule Scanner.NewsView do
  use Scanner.Web, :view

  defdelegate active_when(conn, query, result \\ ~s(class="active")), to: Scanner.LayoutView
  defdelegate pagination_numbers(offset, total), to: Scanner.LayoutView
  defdelegate highlight(text, keyword), to: Scanner.LayoutView
end

web/templates/news/edit.html.eex
<div class="page-header">
  <h2>编辑社保新闻 <small>#<%= @news.id %></small></h2>
</div>

<% text_field = fn key, label -> %>
  <div class="form-group">
    <label for="news_<%= key %>"><%= label %></label>
    <input type="text" name="news[<%= key %>]" class="form-control" id="news_<%= key %>" placeholder="请输入新闻<%= label %>" value="<%= @news |> Map.get(key) %>">
  </div>
<% end %>

<% text_area = fn key, label -> %>
  <div class="form-group">
    <label for="news_<%= key %>"><%= label %></label>
    <textarea type="text" name="news[<%= key %>]" class="form-control" id="news_<%= key %>" placeholder="请输入新闻<%= label %>" rows="4"><%= @news |> Map.get(key) %></textarea>
  </div>
<% end %>

<div class="row">
  <form class="col-md-7" action="<%= news_path(@conn, :update, @news.id) %>" method="post">
    <%= text_field.(:title, "标题") %>
    <%= text_field.(:subtitle, "副标题") %>
    <%= text_field.(:author, "作者") %>
    <%= text_field.(:thumbnail_url, "缩略图链接") %>
    <%= text_field.(:source_url, "原文链接") %>
    <%= text_area.(:content, "文章内容") %>

    <button type="submit" class="btn btn-primary pull-right">Submit</button>
  </form>
</div>

web/templates/news/index.html.eex
<% type = @conn.params["type"] %>
<% search = @conn.params["search"] %>

<div class="row">
  <div class="col-md-3">
    <% titles = %{"policies" => "政策", "notifications" => "通知", "services" => "服务"} %>
    <% subnav_item = fn key -> %>
      <li <%= active_when(@conn, params: %{"type" => key}) %>><a href="<%= news_path(@conn, :index, if(key, do: [type: key], else: [])) %>"><%= titles[key] || "全部类别" %></a></li>
    <% end %>

    <ul class="nav nav-pills nav-stacked">
      <%= subnav_item.(nil) %>
      <%= subnav_item.("policies") %>
      <%= subnav_item.("notifications") %>
      <%= subnav_item.("services") %>
    </ul>
  </div>

  <div class="col-md-9 data-table">
    <div class="page-header">

      <form class="col-xs-4 pull-right" method="GET" action="<%= news_path(@conn, :index) %>">
        <%= if type do %>
          <input type="hidden" name="type" value="<%= type %>">
        <% end %>
        <div class="input-group">
          <input type="text" name="search" class="form-control" placeholder="<%= search || "搜索新闻标题" %>">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">搜索</button>
          </span>
        </div>
      </form><!-- /input-group -->

      <h2>社保新闻 <small><%= titles[type] %></small></h2>
    </div>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>标题</th>
          <th>副标题</th>
          <th>作者</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <%= for n <- @news do %>
          <tr>
            <th><%= n.id %></th>
            <td><%= highlight(n.title, search) %></td>
            <td><%= highlight(n.subtitle, search) %></td>
            <td><%= highlight(n.author, search) %></td>
            <td><a href="<%= news_path(@conn, :edit, n.id) %>">编辑</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row">
      <div class="col-md-6">
        <p class="pagination">从 <%= @start %> 到 <%= @stop %> / 共 <%= @total %> 条数据</p>
      </div>

      <div class="col-md-6">
        <% {start, stop, page, first, last} = pagination_numbers(@start, @total) %>

        <ul class="pagination pull-right">
          <%= if page == first do %>
            <li class="disabled"><span>&laquo;</span></li>
          <% else %>
            <li><a href="<%= news_path(@conn, :index, Map.merge(@conn.params, %{page: page - 1})) %>">&laquo;</a></li>
          <% end %>

          <%= for i <- (start..stop) do %>
            <li <%= if i == page, do: raw ~s(class="active") %>><a href="<%= news_path(@conn, :index, Map.merge(@conn.params, %{page: i})) %>"><%= i %></a></li>
          <% end %>

          <%= if page == last do %>
            <li class="disabled"><span>&raquo;</span></li>
          <% else %>
            <li><a href="<%= news_path(@conn, :index, Map.merge(@conn.params, %{page: page + 1})) %>">&raquo;</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>