config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :welcome, only: :show

  resources :news
  resources :cities
  resources :android_packages do
    member do
      get :qrcode
    end
  end
  resource :audit, only: [] do
    get :identify
    get :people

    get :show, to: redirect('/audit/identify')
  end

  namespace :editormd do
    resources :images, only: :create
  end

  namespace :api, defaults: { format: 'json' } do
    resources :news, only: :index
    resources :cities, only: :index
    resource :identity, only: [] do
      post :identify
      get :abilities
      post :use_count
    end
    resource :update, only: :show
  end

  root to: 'welcomes#show'
end

app/views/layouts/application.html.erb
<% def nav_item title, path, active_params
  active = active_params.all? { |key, value| params[key] == value }
  content_tag :li, active && { class: 'active' } do
    link_to(title, path)
  end
end %>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>中恒联保社保认证 - 控制台</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">社保认证</div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= nav_item "新闻", news_index_path, controller: 'news' %>
            <%= nav_item "区域", cities_path, controller: 'cities' %>
            <%= nav_item "安卓版本", android_packages_path, controller: 'android_packages' %>
            <%= nav_item "审计", audit_path, controller: 'audits' %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div id="falsh-messages" data-turbolinks-permanent>
        <%= flash_messages %>
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <%= yield %>

    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <meta name="robots" content="index, follow">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <title>中恒联保</title>

    <%= stylesheet_link_tag "welcome" %>
  </head>

  <body id="qt-body" class="qt-body">
    <%= yield %>

    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=95f87a7ab38b178d754a7ebdcb685d5c"></script>
    <%= javascript_include_tag "welcome" %>

  </body>
</html>